### ISSUE TITLE
Not loading an EPUB file

### ISSUE THREAD

**Issue by Augusto7743** [troyeguo/koodo-reader#475] opened 2022-05-30 20:53 UTC
### I've already installed the latest developer version of Koodo Reader, this problem still exsits

- [X] Yes

### There are no similar issues on the issue list

- [X] Yes

### I've already read the document, still can't solve it.

- [X] Yes

### Operating system or browser

Ubuntu

### App Version

1.4.3

### Bug Detail

The file test.epub not load.
Please anyone can test in current development release ?
Having internet access problems not allowing download current development version.
Thanks for read.

### Files (Optional)

**Comment by Augusto7743** [comment] 2022-05-30 20:54
the epub file

**Comment by Augusto7743** [comment] 2022-05-30 20:56
another try to upload

**Comment by troyeguo** [comment] 2022-05-31 03:41
Thanks for the feedback, we will fix this in the next update

**Comment by Augusto7743** [comment] 2022-06-03 00:26
I need say thanks very much for you.

**Comment by troyeguo** [comment] 2022-06-26 12:17
Please update to 1.4.5

**Comment by Augusto7743** [comment] 2022-06-27 12:34
Tested using 1.4.5.
Perhaps you had tested only loading the file and "being" loaded was "fixed".
Exactly loading the same epub file above try scroll down using the mouse wheel.
The first pages are scrolled, but after of few pages the document is totally empty not allowing go back or browse in index.
Not is possible read the file in page sequence and need close Koodo Reader.
Trying access in some pages using the index works only one time because after all pages will be empty.

**Comment by troyeguo** [comment] 2022-06-28 03:27
Thanks for the feedback, we will look into it.

**Comment by Augusto7743** [comment] 2022-06-28 07:53
again thanks

**Comment by Xelbayria** [comment] 2022-08-06 02:51
I had the same issue following: 

**OS**: Windows 10 pro (64bit) 
**Version**: 1.4.7
**Type of format**: EPUB
**Size of ebook**: 9.4MB 

There was 1 page where the contents were displayed at the beginning of the book but not all are fully displayed. I suspected that there are issues with font size. I tried to change the font size but I ended up having to reboot the koodo-reader and gave up on trying to change the font size. I decided to check the main content of the book and none of any content shows up. Here are the 2 pictures of the 1 page from 2 different formats (PDF and EPUB) below: 

[Koodo-reader view](https://imgur.com/5cF5e9h) - EPUB
[PDF view](https://imgur.com/1yEbnma) - PDF

I hope this is a good clue for you to find out what's wrong.

**Comment by troyeguo** [comment] 2022-08-07 07:15
> I had the same issue following:
> 
> **OS**: Windows 10 pro (64bit) **App Version**: 1.4.7 **Type of format**: EPUB **Size of ebook**: 9.4MB
> 
> There was 1 page where the contents were displayed at the beginning of the book but not all are fully displayed. I suspected that there are issues with font size. I tried to change the font size but I ended up having to reboot the koodo-reader and gave up on trying to change the font size. I decided to check the main content of the book and none of any content shows up. Here are the 2 pictures of the 1 page from 2 different formats (PDF and EPUB) below:
> 
> **View Mode**: 2-paged view [Koodo-reader view](https://imgur.com/5cF5e9h) - EPUB [PDF view](https://imgur.com/1yEbnma) - PDF
> 
> I hope this is a good clue for you to find out what's wrong.

Can you provide a copy of the book?

**Comment by Xelbayria** [comment] 2022-08-07 18:07
> Can you provide a copy of the book?

[Book.zip](https://github.com/troyeguo/koodo-reader/files/9277252/Book.zip)

Here's the book above.

**Comment by troyeguo** [comment] 2022-08-08 02:03
> > Can you provide a copy of the book?
> 
> [Book.zip](https://github.com/troyeguo/koodo-reader/files/9277252/Book.zip)
> 
> Here's the book above.

Sorry, we can't seem to reproduce this bug. Things look fine on my side. You can try to uninstall and reinstall Koodo, and delete user setting when uninstalling.
![image](https://user-images.githubusercontent.com/13820674/183323797-bb7f3dbf-763e-4017-a31d-5806f5539f80.png)

**Comment by Xelbayria** [comment] 2022-08-09 04:54
> Sorry, we can't seem to reproduce this bug. Things look fine on my side. You can try to uninstall and reinstall Koodo, and 
> delete user setting when uninstalling.

Strange. I think the cause is "Scoop", i installed your software via scoop. 🤔

**Comment by troyeguo** [comment] 2022-08-10 03:19
> > Sorry, we can't seem to reproduce this bug. Things look fine on my side. You can try to uninstall and reinstall Koodo, and
> > delete user setting when uninstalling.
> 
> Strange. I think the cause is "Scoop", i installed your software via scoop. 🤔
> 
> EDIT: ok interesting. I removed the folder of Koodo-reader via %Appdata% and reinstalled the software. it works like what your picture shows. but the problem came when I try to change the `background colour` to "Black" and the `Text colour` to "White" try and see if you can reproduce this bug
> 
> I also noticed the view mode is in "Double" and it's not working properly with EPUB. it's more like 1 page (Single). Here's the picture below: [View Mode (Double)](https://imgur.com/14fi1fd)
> 
> EDIT 2: Via `Setting` -> `Appearance` -> Changed to `Night Mode` This also gives the same problem

This book has built-in background which can't be affected by the setting. When you set the text color to white, the text will blend with the white background, that's why it's not showing properly.

**Comment by troyeguo** [comment] 2022-08-10 03:24
The double mode issue seems to also derive from the book itself, and can only be resolved by upstream library (Epub.js)

**Comment by Xelbayria** [comment] 2022-08-10 07:59
> This book has built-in background which can't be affected by the setting. When you set the text color to white, the text will 
> blend with the white background, that's why it's not showing properly.

I had the same guess as you did except "built-in background". hmm. 

> The double mode issue seems to also derive from the book itself, and can only be resolved by upstream library (Epub.js)

I see. Okay, so which format do you recommend when adding e-books to the Koodo-reader.

**Comment by troyeguo** [comment] 2022-08-11 02:10
Epub still has the best compatibility with Koodo. But given the situation here, I would recommend pdf instead.

**Comment by Xelbayria** [comment] 2022-08-11 17:40
> Epub still has the best compatibility with Koodo. But given the situation here, I would recommend pdf instead.

Alright, Thank you for the answer.

**Comment by Augusto7743** [comment] 2022-08-18 01:08
Tested using 1.4.7.
EPUB file is loaded, but when scrolling not are showed any pages.

**Comment by troyeguo** [comment] 2022-08-18 13:51
> Tested using 1.4.7. EPUB file is loaded, but when scrolling not are showed any pages.

Sorry, we can't reproduce this bug, can you provide any screen recordings.

**Comment by Xelbayria** [comment] 2022-08-21 00:02
> Sorry, we can't reproduce this bug, can you provide any screen recordings.

Strange. Alright, Here are the screen recording: 
[Light Mode setting](https://drive.google.com/file/d/1xAjHIMZFSLaiizAFiYdH7Gk_UmXLA1Gr/view?usp=sharing)
[Dark Mode setting](https://drive.google.com/file/d/1RIFPdHIZsvjkFCr5of5BF-ThqVLg9S49/view?usp=sharing)

Note: You look at the light mode first. You'll see the way Koodo-reader processes the EPUB files. the view mode is not really 2 paged views, but they are more like 1 paged view. 

Here are a bit more details about my PC: 
-Nvidia Geforce 1070GTX  (GPU)
-Asus P8Z68-V pro/Gen 3 (MOTHERBOARD
-Intel I7-2600K (CPU) 

The motherboard and CPU are 11 years old. (I know, so old)

**Comment by troyeguo** [comment] 2022-08-22 04:28
> > Sorry, we can't reproduce this bug, can you provide any screen recordings.
> 
> Strange. Alright, Here are the screen recording: [Light Mode setting](https://drive.google.com/file/d/1xAjHIMZFSLaiizAFiYdH7Gk_UmXLA1Gr/view?usp=sharing) [Dark Mode setting](https://drive.google.com/file/d/1RIFPdHIZsvjkFCr5of5BF-ThqVLg9S49/view?usp=sharing)
> 
> Note: You should look at the light mode first. You'll see the way Koodo-reader processes the EPUB files. the view mode is not really 2 paged views, but they are more like 1 paged view.
> 
> Here are a bit more details about my PC: -Nvidia Geforce 1070GTX (GPU) -Asus P8Z68-V pro/Gen 3 (MOTHERBOARD -Intel I7-2600K (CPU)
> 
> The motherboard and CPU are 11 years old. (I know, so old)

Sorry, I was replying @Augusto7743 's comment.

**Comment by Xelbayria** [comment] 2022-08-22 19:22
> Sorry, I was replying @Augusto7743 's comment.

Ah, that's my mistake. I misjudged the situation. No worries.

**Closed** 2023-07-22 07:21 UTC
Labels: bug
