### ISSUE TITLE
Keyboard shortcut not working after navigating chapter

### ISSUE THREAD

**Issue by thenoobtester** [troyeguo/koodo-reader#279] opened 2021-12-04 09:39 UTC
### I've already installed the latest developer version of Koodo Reader, this problem still exsits

- [X] Yes

### There are no similar issues on the issue list

- [X] Yes

### I've already read the Q&A document, still can't solve it.

- [X] Yes

### Operating system or browser

Other Linux distribution

### App Version

1.3.8

### Bug Detail

Whenever the chapter changes the left and right (also up and down and space bar) don't work anymore to navigate. This issue was declared as fixed in 1.3.5 (which I haven't tried) but apparently it's back in 1.3.8. I used the Appimage and the .deb for Linux, and also the portable version for Windows.

Thank you for your help.

UPDATE:I tried 1.3.6 the stable version and the issue is there too, but sometimes the keyboard shortcuts work which is strange. However in both 1.36 and 1.38 the mouse wheel works all the time which is a good replacement even though the visual effect is not the same. I don't understand why the mouse wheel creates a screen refresh on page change which keyboard keys don't do when they work...

**Comment by troyeguo** [comment] 2021-12-04 13:15
Does this bug still exist in the latest 1.3.9? Sorry  we could reproduce it in the windows version 1.3.9

**Comment by thenoobtester** [comment] 2021-12-04 13:42
It works but randomly like in 1.3.6, I will open a book and it will not work then close it and open it again and it will work but then randomly stops working. I'm trying on simple epubs with just text.

**Comment by troyeguo** [comment] 2021-12-04 13:50
> It works but randomly like in 1.3.6, I will open a book and it will not work then close it and open it again and it will work but then randomly stops working. I'm trying on simple epubs with just text.

Thanks for the reply, we encounter the same issue on epub files too. We will fix it in the next update. Sorry for your inconvenience.

**Comment by thenoobtester** [comment] 2021-12-04 13:56
No worries, thank you for the reply and the great piece of software :)

**Comment by drkui** [comment] 2021-12-10 04:21
I have this same issue and I'm on 1.3.9. I can't use my arrow keys to navigate like before.

**Comment by troyeguo** [comment] 2022-01-02 11:16
Please update to 1.4.0 to see if this bug still exists. This bug still exists in some rare scenarios though.  Like when opening books in the main window and open a epub book after opening a mobi/azw3/txt book. Other than that, we can't reproduce this bug for now.

**Comment by alarcondgtuc** [comment] 2022-06-23 07:48
Same happening for me. I'm using 1.3.9

Left and right arrow keys work fine if I don't resize the window, but whenever I press the button to go full window (not fullscreen) the arrows navigation breaks.

**Comment by troyeguo** [comment] 2022-06-23 23:51
> Same happening for me. I'm using 1.3.9 on Windows 10
> 
> Left and right arrow keys work fine if I don't resize the window, but whenever I press the button to go full window (not fullscreen) the arrows navigation breaks.

this issue has been fixed in 1.4.4

**Comment by alarcondgtuc** [comment] 2022-06-24 02:05
> 
> this issue has been fixed in 1.4.4

Nice! When will it be available as a stable build tho? Is it that unstable for general reading?

**Comment by troyeguo** [comment] 2022-06-25 01:22
We're still testing to make sure it's stable enough. It should be ready in the next 1 or 2 month.

**Closed** 2023-07-22 07:16 UTC
Labels: bug
